name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          wayofdt/linkshortener:latest

    - name: SSH and Deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: 91.223.70.72
        username: ubuntu
        password: ${{ secrets.SERVER_SSH_PASSWORD }}
        script: |
          cd myproject/wayofdt-projects/ && git pull && docker-compose pull linkshortener && docker-compose up -d --no-deps linkshortener && docker image prune -f && cd ../..
